version: 2.1
orbs:
codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run:
          name: Run tests and collect coverage
          command: mvn -B test
      - run:
          name: Upload CodeCov.io Data
          command: bash <(curl -s https://codecov.io/bash) -F unittests
          when: always # Uploads code coverage results, pass or fail


workflow:
  version: 2.1
  build-test:
    jobs:
      - build
